# Generated by Django 5.2.10 on 2026-02-02 16:33

import django.db.models.deletion
import master.models
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='My Logistics Company', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicon/')),
                ('country', models.CharField(blank=True, default='United States', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='California', max_length=100, null=True)),
                ('address', models.TextField(blank=True, default='123 Logistics Blvd, Suite 101, San Francisco, CA, 94101', null=True)),
                ('phone', models.CharField(blank=True, default='+1 800 555 1234', max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='info@logisticscompany.com', max_length=254, null=True, verbose_name='Email')),
                ('PAN', models.CharField(blank=True, default='ABCPQ1234D', max_length=200, null=True, verbose_name='PAN')),
            ],
            options={
                'verbose_name': 'Singleton Setting',
                'verbose_name_plural': 'Singleton Settings',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBranch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('branch_id', models.CharField(blank=True, db_index=True, default=master.models.generate_branch_code, max_length=20, null=True, verbose_name='Branch ID')),
                ('name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='operational', max_length=20, verbose_name='Status')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('is_main_branch', models.BooleanField(default=False, verbose_name='Is Main Branch')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Branch',
                'verbose_name_plural': 'historical Branches',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMasterData',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type_master', models.CharField(choices=[('INCO', 'INCO'), ('STATUS', 'STATUS'), ('CONTAINER_TYPE', 'CONTAINER_TYPE'), ('CARGO_TYPE', 'CARGO_TYPE'), ('TRAILER_TYPE', 'TRAILER_TYPE'), ('DELIVERY_TYPE', 'DELIVERY_TYPE'), ('ShipmenSubType', 'ShipmenSubTyp'), ('INCO', 'INCO')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical master data',
                'verbose_name_plural': 'historical master datas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_master', models.CharField(choices=[('INCO', 'INCO'), ('STATUS', 'STATUS'), ('CONTAINER_TYPE', 'CONTAINER_TYPE'), ('CARGO_TYPE', 'CARGO_TYPE'), ('TRAILER_TYPE', 'TRAILER_TYPE'), ('DELIVERY_TYPE', 'DELIVERY_TYPE'), ('ShipmenSubType', 'ShipmenSubTyp'), ('INCO', 'INCO')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type_master', 'name'], name='master_mast_type_ma_cfbd6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(blank=True, default=master.models.generate_branch_code, max_length=20, null=True, unique=True, verbose_name='Branch ID')),
                ('name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='operational', max_length=20, verbose_name='Status')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('is_main_branch', models.BooleanField(default=False, verbose_name='Is Main Branch')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_branch_association', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['branch_id'], name='branch_id_idx'), models.Index(fields=['name'], name='branch_name_idx')],
            },
        ),
    ]
